### ISSUE TITLE
Decode

### ISSUE THREAD

**Issue by SrMouraSilva** [PedalController/MidiMultistompController#1]
## Material

* https://github.com/PedalController/MidiPedalController/issues/1#issue-211466770
* https://www.dropbox.com/s/z05pzz5wnebcc2y/Zoom%20MS70-CDR%20MIDI%20specification.rtf?dl=0
* https://github.com/g200kg/zoom-ms-utility/blob/master/index.html#L3705-L3726

## Decode list
* [ ] Global -> AutoSave
```
F0 52 00 5A 31 06 0A 00 00 F7
F0 52 00 5A 31 06 0A 01 00 F7
```

* [ ] Global -> Tempo
```
F0 52 00 5A 31 06 08 vl 00 F7
```

* [ ] Sig. Path
```
F0 52 00 5A 31 06 09 00 00 F7
F0 52 00 5A 31 06 09 01 00 F7
```

* [x] Total -> Name
```
F0 52 00 5A 31 07 lt vl 00 F7
# lt - letra 0-9
# vl - valor caractere ASCII
```

* [x] Total -> Level
```
F0 52 00 5A 31 06 02 vl 00 F7
```

* [ ] Total swap
* [ ] Total CTRL SW/PDL (ControlSwitch/PDL)
```
F0 52 00 5A 31 06 06 vl 00 F7
# vl - [00-08]
```

* [ ] Total -> PDL DST -> 1° param - Assign
* [ ] Total -> PDL DST -> 2° param - Aberto
```
F0 52 00 5A 31 06 04 vl 00 F7
# vl - Depende do primeiro parâmetro
```

* [ ] Total -> PDL DST -> 3° param - Fechado
```
F0 52 00 5A 31 06 05 vl 00 F7
# vl - Depende do primeiro parâmetro
```

* [ ] Store -> Store
```F0 52 00 5A 32 01 00 00 5F 00 00 00 00 00 F7```
* [ ] Store -> Swap
```F0 52 00 5A 32 02 00 00 5F 00 00 60 00 00 F7```
* [ ] Ativar efeito - Comando grande
* [ ] Desativar
```F0 52 00 5A 31 [effect] 00 00 00 F7```
* [ ] Trocar efeito - Comando grande
* [ ] Trocar de banco - Comando Pequeno (CC 00, CC 32, PC [patch number])
* [ ] Alterar parâmetro - Comando Grande

**Comment by mungewell** [comment]
Working with another project to add effects into the f/w of Zoom pedals.
https://github.com/Barsik-Barbosik/Zoom-Firmware-Editor

Do you have logs/more info on how the effects are 'Activated/Deactivated' as you mention above.... what is the 'Comando grande'?

**Comment by SrMouraSilva** [comment]
Hello @mungewell.

> Do you have logs/more info on how the effects are 'Activated/Deactivated' as you mention above...

Se this thread. There is a compilation of information about Zoom messages (in English)
https://github.com/PedalController/MidiPedalController/issues/1#issue-211466770

> what is the 'Comando grande'?

The "Comando grande" or "big string" is a string that retuns all path data. When a effect is enabled(activated), as eg, the Zoom G3 returns all patch data.

In Zoom MS50g/60CDR/70B, there is the following specification https://github.com/g200kg/zoom-ms-utility/blob/master/midimessage.md#patch-data-format

**Comment by mungewell** [comment]
Thanks for the response, seems that you are describing process when an effect is Selected/Bypassed.

I am interested in finding out a new effect (not previously on pedal) can be Installed/Removed (ie via GuitarLab). I know this is possible on the G1Four, but it might not be possible on MultiStomps.

**Comment by SrMouraSilva** [comment]
> Thanks for the response, seems that you are describing process when an effect is Selected/Bypassed.

Yes, is this

> I am interested in finding out a new effect (not previously on pedal) can be Installed/Removed (ie via GuitarLab). I know this is possible on the G1Four, but it might not be possible on MultiStomps.

Ah, ok!
